Repository NishantRana07/HrRoadways, pull requests merged in 2025-08, with the labels that each got.

#461 [Feature] ✨ To improve the site rendering speed and optimize the website
  src/App.jsx
Labels: gssoc25, Level 2

#485 Added toast message on successful login & SignOut in UserProfile; cleanup code;
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login.jsx
  src/components/SignUp.jsx
  src/components/ToastTest.jsx
  src/components/Userprofile.jsx
  src/components/WeatherUpdates.jsx
  src/components/nav.jsx
Labels: gssoc25, Level 2

#516 updated the count of thumbs up in the blog page
  .vscode/launch.json
  package-lock.json
  src/components/Blog.jsx
Labels: gssoc25, Level 1

#511 Fix : Gender text color fixed
  src/components/BookingPage.jsx
Labels: Level 1

#503 Added working social media links
  src/components/footer.jsx
  src/utils/translationKeyMap.js
Labels: gssoc25, Level 1

#519 [DOCS] Revamp README – Remove Repetition, Add Contributing Section & Back to Top Button
  README.md
Labels: gssoc25, Level 1

#546 feat: added new UI animations
  package-lock.json
  src/components/Trip.jsx
Labels: Easy, gssoc25, Level 1, OSCI'25, 🌟.
