Repository NishantRana07/HrRoadways, pull requests merged in 2025-07, with the labels that each got.

#265 Fix: Handle client-side routing 404 on Vercel by adding vercel.json
  vercel.json
  vite.config.js
Labels: dependencies, gssoc25, Level 2

#290 Fix: Display issues for Technology Stack images & Travel Locations page and Added Filer
  src/assets/translations.json
  src/components/TravelLocation.jsx
Labels: Frontend, Backend, gssoc25, Level 3

#343 Fix: Blog page fixed
  src/components/Blog.jsx
Labels: enhancement, Frontend, gssoc25, Level 2

#385 Add scroll to top button
  src/App.jsx
  src/components/ScrollButton.jsx
Labels: enhancement, gssoc25, Level 2

#387 Plan jounery detailed page
  src/App.jsx
  src/components/HotelDetail.jsx
  src/components/Trip.jsx
  src/components/WeatherUpdates.jsx
  src/components/footer.jsx
  src/data/hotelsData.js
  src/index.css
  src/styles/BusCard.css
  src/styles/bookingPage.css
  src/styles/footer-new.css
  src/styles/footer.css
  src/styles/hero.css
  src/styles/modal.css
  src/styles/nav.css
Labels: enhancement, Frontend, gssoc25, Level 2

#372 Implement functional Affiliate Program page
  TranslationLink.md
  src/components/AffiliateProgram.jsx
Labels: enhancement, Easy, Frontend, gssoc25, Level 2

#395 Fix: Added an fix for multiple API calls for getting weather data for…
  src/components/WeatherUpdates.jsx
  src/main.jsx
Labels: Backend, gssoc25, Level 2

#396 Auth frontend
  package.json
  src/App.jsx
  src/components/ForgotPassword.jsx
  src/components/Login.jsx
  src/components/ProtectedRoute.jsx
  src/components/Register.jsx
  src/components/Userprofile.jsx
  src/components/nav.jsx
  src/i18n/locales/en.json
  src/i18n/locales/hi.json
  src/store/store.js
Labels: Database, Backend, gssoc25, Level 3

#402 Fix:Updated broken image links with new ones in travellocations route
  src/assets/translations.json
  src/components/TravelLocation.jsx
Labels: enhancement, Frontend, gssoc25, Level 1

#419 contribution-template
  src/App.jsx
Labels: enhancement, Frontend, gssoc25, Level 2

#403 fix: scroll position now resets on route change
  src/App.jsx
  src/components/ScrollToTop.jsx
Labels: enhancement, Frontend, gssoc25, Level 2

#405 Fix:Updated input text color for better readability
  eslint.config.js
  src/App.jsx
  src/components/BestRides.jsx
  src/components/Blog.jsx
  src/components/BookingPage.jsx
  src/components/BusCard.jsx
  src/components/DonatePage.jsx
  src/components/HelpLinepage.jsx
  src/components/Paymentoptions.jsx
  src/components/RoyalHaryanaTourism.jsx
  src/components/Timetable.jsx
  src/components/TravelLocation.jsx
  src/components/WeatherUpdates.jsx
  src/components/hero.jsx
  tailwind.config.js
Labels: enhancement, Frontend, gssoc25, Level 2
