Repository NishantRana07/HrRoadways, pull requests merged in 2025-01, with the labels that each got.

#11 fix: Image visibility issue
  src/assets/BusCard.css
Labels: good first issue, AcWoc, Easy

#12 fix: images rendering resolved
  src/assets/BusCard.css
  src/assets/hr_bus.png
  src/components/BusCard.jsx
Labels: good first issue, AcWoc, Easy

#16 Update README.md
  README.md
Labels: documentation, AcWoc, Medium

#20 footer is added
  src/App.jsx
  src/components/Aboutus.jsx
  src/components/footer.jsx
Labels: enhancement, AcWoc, Medium

#24 Add Toggle Button Logic for Language Switching (#1)
  src/App.jsx
  src/assets/Trip.css
  src/components/Aboutus.jsx
  src/components/BusCard.jsx
  src/components/Trip.jsx
  src/components/footer.jsx
  src/components/hero.jsx
  src/components/nav.jsx
  src/main.jsx
Labels: good first issue, AcWoc, Hard

#25 Issue #23 Solved
  src/assets/LogoHR.png
  src/assets/hero.css
  src/components/hero.jsx
Labels: enhancement, AcWoc, Hard

#32 Updated Twitter icon
  src/components/footer.jsx
Labels: enhancement, AcWoc, Easy

#36 Updated Favicon icon and title
  index.html
Labels: enhancement, AcWoc, Easy

#37 ⬆️ Adding a Scroll-to-Top Button to the Homepage
  index.html
  script.js
  style.css
Labels: enhancement, AcWoc, Medium

#38 Add files via upload
  public/Places/Banglore.json
Labels: AcWoc, Easy, Database

#39 Add blog section
  src/App.jsx
  src/assets/Blog.css
  src/components/Blog.jsx
Labels: enhancement, AcWoc, Hard

#42 Add your city bus routes
  Database/YourCity/BusData.json
Labels: enhancement, AcWoc, Easy

#43 Added Scroll to top functionality
  src/App.jsx
Labels: enhancement, AcWoc, Medium

#44 Homepage Functionalities added
  index.html
  package.json
  postcss.config.js
  src/App.jsx
  src/assets/nav.css
  src/components/footer.jsx
  src/components/hero.jsx
  src/components/nav.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: enhancement, AcWoc, Hard

#46 Navigation Bar updated
  src/components/nav.jsx
Labels: enhancement, AcWoc, Medium

#48 Add files via upload
  public/Places/Bhopal.json
  public/Places/Sehore.json
Labels: AcWoc, Medium, Database

#50 Fix Hindi-English button functionality
  src/assets/nav.css
  src/components/nav.jsx
Labels: enhancement, AcWoc, Medium

#51 Update index.html
  index.html
Labels: enhancement, AcWoc, Easy

#53 Updated twitter icon
  package-lock.json
  src/components/footer.jsx
Labels: bug, AcWoc, Easy

#58 #52, Translation restored
  src/App.jsx
  src/assets/Blog.css
  src/assets/hero.css
  src/assets/nav.css
  src/components/Aboutus.jsx
  src/components/Blog.jsx
  src/components/hero.jsx
  src/components/nav.jsx
  src/index.css
Labels: enhancement, AcWoc, Hard

#57 trip page ui updated
  src/components/Trip.jsx
  src/components/nav.jsx
Labels: enhancement, AcWoc, Medium

#60 Add files via upload
  public/Places/Indore.json
  public/Places/banglore main.json
  public/Places/chennai.json
  public/Places/delhi.json
  public/Places/hyderabad.json
  public/Places/kolkata.json
  public/Places/mumbai.json
  public/Places/pune.json
Labels: AcWoc, Medium, Database

#65 #31, team member photos now visible
  src/assets/team-member1.png
  src/assets/team-member2.png
  src/assets/team-member3.png
  src/components/Aboutus.jsx
Labels: enhancement, AcWoc, Medium

#68 Added Donate page and blog page UI Improv
  package-lock.json
  src/App.jsx
  src/assets/Blog.css
  src/assets/DonatePage.css
  src/components/Blog.jsx
  src/components/DonatePage.jsx
  src/components/nav.jsx
Labels: enhancement, AcWoc, Hard

#69 new: Travel Locations Component added
  src/App.jsx
  src/assets/GURGAON.jpg
  src/assets/Kurukshetra.jpg
  src/assets/Morni_Hills.webp
  src/assets/Panchkula.jpg
  src/assets/Pinjore_Gardens.avif
  src/assets/Sultanpur_National_Park.webp
  src/assets/Surajkund.jpg
  src/assets/TravelLocations.css
  src/components/TravelLocation.jsx
  src/components/nav.jsx
Labels: enhancement, AcWoc, Medium

#70 Restructured
  Databases/BusData.json
Labels: AcWoc, Easy

#79 contact page updated
  libs/utils.js
  src/App.jsx
  src/assets/Trip.css
  src/components/HelpLinepage.jsx
  src/components/Trip.jsx
  src/index.css
Labels: enhancement, AcWoc, Hard

#80 Blog page UI enhanced and few functionalities added
  src/components/Blog.jsx
Labels: enhancement, AcWoc, Hard

#91 Added faq page
  src/App.jsx
  src/components/faq.jsx
  src/components/footer.jsx
Labels: enhancement, AcWoc, Medium

#93 Features added in the Donations Page
  src/components/DonatePage.jsx
Labels: enhancement, AcWoc, Medium

#96 aboutus page made more dynamic and updated
  src/components/Aboutus.jsx
Labels: AcWoc, Medium, Frontend

#100 #84 solved - Footer is fully fuctional
  src/assets/DonatePage.css
  src/assets/TravelLocations.css
  src/assets/footer.css
  src/components/DonatePage.jsx
  src/components/HelpLinepage.jsx
  src/components/TravelLocation.jsx
  src/components/faq.jsx
  src/components/footer.jsx
Labels: AcWoc, Medium, Frontend

#121 #97 Affiliate Program Page applied
  package-lock.json
  src/App.jsx
  src/assets/AffiliateProgram.css
  src/components/AffiliateProgram.jsx
  src/components/footer.jsx
Labels: AcWoc, Medium, Frontend

#126 Traffic and other alert added on homepage
  src/components/TrafficUpdates.jsx
  src/components/hero.jsx
Labels: AcWoc, Medium, Frontend

#127 footer updated
  src/components/footer.jsx
Labels: AcWoc, Medium, Frontend

#131 #123 Home, Footer Layout and code readability fixed
  src/assets/footer.css
  src/assets/hero.css
  src/components/footer.jsx
  src/components/hero.jsx
Labels: enhancement, AcWoc, Hard, Frontend

#140 All issues in #98 addressed
  Databases/Haryana.json
  src/App.jsx
  src/assets/hero.css
  src/components/hero.jsx
Labels: AcWoc, Hard, Frontend, Backend

#144 Popular Routes section Updated
  package.json
  src/components/PopularRoutes.jsx
  src/components/hero.jsx
Labels: AcWoc, Medium, Frontend

#147 #142 complete Footer is now responsive
  package-lock.json
  src/assets/footer.css
  src/components/footer.jsx
Labels: AcWoc, Medium, Frontend

#155 policy page updated and features added
  src/components/InfoPage.jsx
  src/components/policy.jsx
Labels: enhancement, AcWoc, Medium, Frontend

#153 To add some features and fixing the bugs
  script.js
  style.css
Labels: enhancement, AcWoc, Medium

#163 All pages are in Hindi now
  src/App.jsx
  src/components/ContactUs.jsx
  src/components/DonatePage.jsx
  src/components/InfoPage.jsx
  src/components/Paymentoptions.jsx
  src/components/RoyalHaryanaTourism.jsx
  src/components/Services.jsx
  src/components/Track.jsx
Labels: AcWoc, Hard, Frontend

#168 #160 Done Bugs reomoved on home page
  src/App.jsx
  src/components/PopularRoutes.jsx
  src/components/Schedule.jsx
  src/components/SearchWindow.jsx
  src/components/hero.jsx
  src/components/nav.jsx
  src/styles/hero.css
  src/styles/schedule.css
Labels: enhancement, AcWoc, Hard, Frontend

#177 Update nav.css
  src/styles/nav.css
Labels: enhancement, AcWoc, Easy

#178 Update footer.css
  src/styles/footer.css
Labels: AcWoc, Easy, Frontend

#184 Update AffiliateProgram.css
  src/styles/AffiliateProgram.css
Labels: AcWoc, Hard, Frontend

#204 Update HelpLinepage.jsx
  src/components/HelpLinepage.jsx
Labels: AcWoc, Medium, Frontend

#206 #187 Donate Page Update Completed
  src/assets/HR_QR.png
  src/components/DonatePage.jsx
Labels: AcWoc, Medium, Frontend

#208 Update policy.jsx
  src/components/policy.jsx
Labels: enhancement, AcWoc, Medium, Frontend
